apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    svc: api-gateway
    app: delinkcious
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: api-gateway
      app: delinkcious
  template:
    metadata:
      labels:
        svc: api-gateway
        app: delinkcious
    spec:
      containers:
      - name: api-gateway
        image: boldfaced7/delinkcious-api-gateway:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port:  80
    targetPort: 5000
  selector:
    svc: api-gateway
    app: delinkcious